import random
import datetime
from django.core.management.base import BaseCommand
from SpellingBee_app.models import Spellbee

# Words categorized by length (5, 7, and 9 letters)
FIVE_LETTER_WORDS = [
    # Nature and Environment
    ("earth", "The earth orbits around the sun."),
    ("water", "Clean water is essential for life."),
    ("cloud", "The cloud looked like a fluffy sheep."),
    ("storm", "A storm brought heavy rain."),
    ("flame", "The flame flickered in the wind."),
    ("frost", "Frost covered the morning grass."),
    ("river", "The river flows to the sea."),
    ("ocean", "The ocean is deep and blue."),
    ("grass", "The grass needs to be cut."),
    ("plant", "A plant needs sunlight to grow."),
    # Animals
    ("tiger", "The tiger prowled through the jungle."),
    ("eagle", "An eagle soared high in the sky."),
    ("whale", "The whale breached the ocean surface."),
    ("snake", "A snake slithered through the grass."),
    ("mouse", "The mouse nibbled on some cheese."),
    ("horse", "The horse galloped across the field."),
    ("sheep", "The sheep grazed in the meadow."),
    ("goose", "The goose swam in the pond."),
    ("camel", "The camel crossed the desert."),
    ("zebra", "The zebra has black and white stripes."),
    # Food and Cooking
    ("bread", "Fresh bread smells wonderful."),
    ("fruit", "An apple is a healthy fruit."),
    ("sweet", "The candy was sweet and delicious."),
    ("spice", "Add some spice to the curry."),
    ("cream", "Ice cream is a cold treat."),
    ("pasta", "The pasta was cooked perfectly."),
    ("pizza", "Hot pizza tastes delicious."),
    ("salad", "Fresh salad is healthy."),
    ("juice", "Orange juice is refreshing."),
    ("sugar", "Add sugar to make it sweet."),
    # School and Learning
    ("learn", "We learn something new every day."),
    ("study", "It's important to study well."),
    ("write", "Students write stories in class."),
    ("think", "Take time to think carefully."),
    ("solve", "Can you solve this math problem?"),
    ("brain", "The brain controls all body functions."),
    ("clock", "The clock shows us the time."),
    ("board", "Write on the board please."),
    ("chalk", "Use chalk to write clearly."),
    ("paper", "Draw on the paper."),
    # Emotions and Qualities
    ("happy", "She felt happy after receiving good news."),
    ("brave", "The brave soldier protected his team."),
    ("smart", "The smart student solved the puzzle quickly."),
    ("peace", "World peace is everyone's dream."),
    ("smile", "Her smile brightened the room."),
    ("quiet", "The library was quiet and peaceful."),
    ("proud", "Parents are proud of their children."),
    ("laugh", "The joke made everyone laugh."),
    ("dream", "Chase your dream with determination."),
    ("shine", "Stars shine brightly at night."),
    # Home and Daily Life
    ("clean", "Keep your room clean and tidy."),
    ("light", "Turn on the light please."),
    ("green", "The grass is green after rain."),
    ("house", "The house has a red roof."),
    ("table", "Put books on the table."),
    ("chair", "Sit on the chair properly."),
    ("phone", "Call me on my phone."),
    ("sleep", "Get enough sleep each night."),
    ("dress", "Wear a warm dress today."),
    ("watch", "Check the time on your watch."),
    # Arts and Entertainment
    ("music", "The music filled the concert hall."),
    ("dance", "They dance gracefully on stage."),
    ("paint", "Children paint colorful pictures."),
    ("song", "She sang a beautiful song."),
    ("story", "Read a story before bed."),
    ("movie", "Watch a movie with friends."),
    ("stage", "Perform on the stage."),
    ("drama", "Act in the school drama."),
    ("flute", "Play the flute softly."),
    ("piano", "Learn to play piano."),
    # Additional words
    ("sport", "Play your favorite sport today."),
    ("score", "Keep track of your score."),
    ("team", "Work well with your team."),
    ("game", "The game was exciting."),
    ("race", "Run the race with speed."),
    ("jump", "Jump as high as you can."),
    ("swim", "Swim in the cool pool."),
    ("kick", "Kick the ball hard."),
    ("catch", "Catch the flying ball."),
    ("throw", "Throw the ball straight."),
    ("color", "What's your favorite color?"),
    ("shape", "Draw different shapes."),
    ("round", "The ball is round."),
    ("sharp", "The pencil is sharp."),
    ("point", "Point to the answer."),
    ("sound", "Listen to the sound."),
    ("noise", "Make less noise please."),
    ("voice", "Speak in a clear voice."),
    ("touch", "Don't touch hot things."),
    ("taste", "Taste the sweet honey."),
    ("smell", "Smell the fresh flowers."),
    ("sight", "Keep things in sight."),
    ("sense", "Use your common sense."),
    ("world", "Travel around the world."),
    ("globe", "Study the globe carefully."),
    ("space", "Explore outer space."),
    ("moon", "The moon shines at night."),
    ("star", "Wish upon a star."),
    ("sun", "The sun gives us light."),
    ("sky", "Look up at the sky."),
    ("lunch", "Eat a healthy lunch."),
    ("drink", "Drink plenty of water."),
    ("plate", "Put food on your plate."),
    ("spoon", "Use your spoon properly."),
    ("fork", "Hold the fork correctly."),
    ("knife", "Be careful with the knife."),
    ("glass", "Fill the glass with juice."),
    ("bowl", "Eat soup from the bowl."),
    ("cook", "Help mom cook dinner."),
    ("bake", "Bake a cake today."),
    ("wash", "Wash your hands well."),
    ("soap", "Use soap to clean."),
    ("towel", "Dry with a clean towel."),
    ("brush", "Brush your teeth daily."),
    ("comb", "Comb your hair neatly."),
    ("dress", "Dress neatly for school."),
    ("shirt", "Iron your shirt well."),
    ("pants", "Wear clean pants."),
    ("shoes", "Tie your shoes properly."),
    ("socks", "Wear matching socks."),
    ("watch", "Watch the time closely."),
    ("clock", "The clock strikes twelve."),
    ("time", "Time flies quickly."),
    ("hour", "Wait for one hour."),
    ("minute", "Just a minute please."),
    ("week", "See you next week."),
    ("month", "This month is June."),
    ("year", "Happy New Year!"),
    ("date", "What's today's date?"),
    ("day", "Have a nice day!"),
    ("phone", "Answer the phone call."),
    ("table", "Sit at the table."),
    ("chair", "Sit on your chair."),
    ("desk", "Clean your desk well."),
    ("lamp", "Turn on the lamp."),
    ("light", "Switch off the light."),
    ("door", "Close the door please."),
    ("wall", "Paint the wall blue."),
    ("floor", "Sweep the floor clean."),
    ("roof", "Fix the roof leak."),
    ("plant", "Water the plant daily."),
    ("grass", "Cut the grass short."),
    ("tree", "Climb the tall tree."),
    ("leaf", "A leaf fell down."),
    ("seed", "Plant a new seed."),
    ("bird", "The bird flies high."),
    ("fish", "Feed the fish daily."),
    ("duck", "The duck swims well."),
    ("frog", "The frog jumps far."),
    ("bear", "The bear is strong."),
    # Additional words for extended period
    ("beach", "Walk on the sandy beach."),
    ("brush", "Brush your teeth daily."),
    ("chest", "Open the treasure chest."),
    ("clock", "The clock shows time."),
    ("cloud", "Look at the white cloud."),
    ("coast", "Live near the coast."),
    ("dance", "Dance to the music."),
    ("dream", "Have a sweet dream."),
    ("drink", "Drink fresh water."),
    ("eagle", "The eagle flies high."),
    ("earth", "Save our planet earth."),
    ("field", "Play in the green field."),
    ("flame", "The flame burns bright."),
    ("flash", "A flash of lightning."),
    ("float", "Boats float on water."),
    ("flood", "Heavy rain caused flood."),
    ("floor", "Clean the floor well."),
    ("flute", "Play the flute softly."),
    ("force", "Use force wisely."),
    ("frame", "Put photo in frame."),
    ("fresh", "Eat fresh fruits."),
    ("frost", "Winter brings frost."),
    ("fruit", "An apple is a fruit."),
    ("ghost", "Tell ghost stories."),
    ("globe", "Spin the world globe."),
    ("grace", "Move with grace."),
    ("grain", "Store grain safely."),
    ("grape", "Purple sweet grape."),
    ("grass", "Cut the lawn grass."),
    ("grave", "Visit the grave yard."),
    ("great", "Do great things."),
    ("green", "Trees are green."),
    ("grind", "Grind the coffee beans."),
    ("group", "Work in a group."),
    ("guard", "Guard the entrance."),
    ("guess", "Guess the answer."),
    ("guide", "Follow the guide."),
    ("heart", "Keep your heart healthy."),
    ("horse", "Ride the horse."),
    ("hotel", "Stay at the hotel."),
    # More additional words
    ("knife", "Use the knife carefully."),
    ("knock", "Knock on the door."),
    ("label", "Read the label."),
    ("laugh", "Laugh with joy."),
    ("learn", "Learn new things."),
    ("leave", "Leave for school."),
    ("lemon", "Squeeze the lemon."),
    ("level", "Reach next level."),
    ("light", "Turn on the light."),
    ("limit", "Know your limit."),
    ("local", "Buy local food."),
    ("logic", "Use your logic."),
    ("lunch", "Eat your lunch."),
    ("magic", "Do magic tricks."),
    ("match", "Match the pairs."),
    ("medal", "Win a gold medal."),
    ("metal", "Metal is strong."),
    ("meter", "Measure in meter."),
    ("money", "Save your money."),
    ("month", "A month has passed."),
    ("motor", "The motor runs."),
    ("mouse", "The mouse clicks."),
    ("mouth", "Open your mouth."),
    ("music", "Play the music."),
    ("nerve", "Have some nerve."),
    ("noise", "Reduce the noise."),
    ("north", "Go to the north."),
    ("nurse", "The nurse helps."),
    ("ocean", "Swim in the ocean."),
    ("offer", "Make an offer."),
    # Final set of words
    ("paint", "Paint the wall."),
    ("paper", "Write on paper."),
    ("party", "Join the party."),
    ("patch", "Patch the hole."),
    ("pause", "Pause the game."),
    ("peace", "Pray for peace."),
    ("phone", "Use the phone."),
    ("photo", "Take a photo."),
    ("piano", "Play the piano."),
    ("piece", "A piece of cake."),
    ("pilot", "The pilot flies."),
    ("place", "Find your place."),
    ("plain", "Plain and simple."),
    ("plane", "The plane soars."),
    ("plant", "Plant a tree."),
    ("plate", "Clean the plate."),
    ("point", "Point the way."),
    ("power", "Save power."),
    ("press", "Press gently."),
    ("price", "Check the price."),
    ("print", "Print the page."),
    ("prize", "Win the prize."),
    ("proof", "Show the proof."),
    ("proud", "Feel proud."),
    ("pulse", "Check the pulse."),
    ("punch", "Punch the bag."),
    ("pupil", "The pupil learns."),
    ("queen", "The queen rules."),
    ("quick", "Be quick."),
    ("quiet", "Stay quiet."),
    # Final set of additional five-letter words
    ("radio", "Turn on the radio."),
    ("raise", "Raise your hand."),
    ("range", "Wide range of options."),
    ("rapid", "Rapid development."),
    ("ratio", "Calculate the ratio."),
    ("reach", "Reach for the stars."),
    ("react", "React to changes."),
    ("ready", "Get ready now."),
    ("refer", "Refer to the manual."),
    ("relax", "Time to relax."),
    ("reply", "Reply to messages."),
    ("right", "Turn right here."),
    ("river", "Cross the river."),
    ("robot", "Program the robot."),
    ("rough", "Rough surface here."),
    ("round", "Round and round."),
    ("route", "Take this route."),
    ("royal", "Royal treatment."),
    ("rural", "Rural lifestyle."),
    ("scale", "Scale the wall."),
    ("scene", "Beautiful scene."),
    ("scope", "Project scope."),
    ("score", "High score achieved."),
    ("scout", "Scout the area."),
    ("screw", "Tighten the screw."),
    ("sense", "Make sense now."),
    ("serve", "Serve others well."),
    ("shade", "Sit in the shade."),
    ("shake", "Shake hands now."),
    ("shape", "Good shape here."),
    ("share", "Share with others."),
    ("sharp", "Sharp knife here."),
    ("sheep", "Count the sheep."),
    ("shell", "Sea shell found."),
    ("shift", "Shift gears now."),
    ("shine", "Stars shine bright."),
    ("shirt", "Clean shirt here."),
    ("shock", "Shock and awe."),
    ("shoot", "Shoot the ball."),
    ("shore", "Walk on shore."),
    ("short", "Short and sweet."),
    ("shout", "Shout for help."),
    ("sight", "Beautiful sight."),
    ("silly", "Silly behavior."),
    ("skill", "Improve your skill."),
    ("skirt", "Wear a skirt."),
    ("sleep", "Time to sleep."),
    ("slice", "Slice the bread."),
    ("slide", "Slide down here."),
    ("smart", "Smart thinking."),
]

SEVEN_LETTER_WORDS = [
    # Nature and Environment
    ("rainbow", "A rainbow appeared after rain."),
    ("sunrise", "The sunrise was beautiful."),
    ("sunset", "We watched the sunset together."),
    ("volcano", "The volcano erupted loudly."),
    ("tornado", "A tornado is very powerful."),
    ("weather", "Check the weather forecast."),
    ("thunder", "Thunder boomed in the sky."),
    ("climate", "The climate is changing."),
    ("glacier", "The glacier moves slowly."),
    ("monsoon", "Monsoon brings heavy rain."),
    # Animals
    ("dolphin", "The dolphin jumped through waves."),
    ("penguin", "The penguin waddled on ice."),
    ("octopus", "An octopus has eight arms."),
    ("giraffe", "The giraffe has a long neck."),
    ("elephant", "An elephant never forgets."),
    ("cheetah", "The cheetah runs very fast."),
    ("ostrich", "An ostrich cannot fly."),
    ("peacock", "The peacock has beautiful feathers."),
    ("squirrel", "The squirrel collected nuts."),
    ("raccoon", "A raccoon washed its food."),
    # Precious Items
    ("diamond", "The diamond sparkled brightly."),
    ("crystal", "The crystal was clear and pure."),
    ("emerald", "An emerald is green in color."),
    ("sapphire", "The sapphire was deep blue."),
    ("jewelry", "She wore beautiful jewelry."),
    ("treasure", "Pirates seek treasure."),
    ("present", "Open your birthday present."),
    ("fortune", "Good fortune smiled upon them."),
    ("precious", "Time is precious, use it well."),
    ("valuable", "Keep valuable items safe."),
    # Education
    ("science", "Science helps us understand nature."),
    ("history", "History teaches us important lessons."),
    ("grammar", "Good grammar improves writing."),
    ("spelling", "Spelling bees test word knowledge."),
    ("reading", "Reading opens new worlds."),
    ("writing", "Writing helps express thoughts."),
    ("drawing", "Drawing is a form of art."),
    ("teacher", "The teacher explains clearly."),
    ("student", "Every student can succeed."),
    ("library", "Visit the library often."),
    # Activities
    ("achieve", "Work hard to achieve your goals."),
    ("believe", "You must believe in yourself."),
    ("improve", "Practice helps improve skills."),
    ("journey", "Life is a journey of learning."),
    ("success", "Hard work leads to success."),
    ("singing", "Singing brings joy to people."),
    ("dancing", "Dancing is good exercise."),
    ("running", "Running keeps you healthy."),
    ("playing", "Playing sports is fun."),
    ("cooking", "Cooking is a useful skill."),
    # Qualities and Concepts
    ("comfort", "The soft bed provided comfort."),
    ("develop", "Plants develop from tiny seeds."),
    ("explore", "Let's explore the new city."),
    ("picture", "She took a picture of the sunset."),
    ("respect", "Show respect to your elders."),
    ("support", "Friends support each other."),
    ("welcome", "They welcome new ideas."),
    ("wonder", "Children wonder about everything."),
    ("balance", "Maintain balance in your life."),
    ("harmony", "Music creates harmony."),
    # Technology
    ("computer", "The computer needs repair."),
    ("internet", "Connect to the internet."),
    ("website", "Visit our school website."),
    ("program", "Learn to program computers."),
    ("network", "Join our social network."),
    ("software", "Install new software."),
    ("digital", "We live in a digital age."),
    ("wireless", "Use the wireless connection."),
    ("keyboard", "Type on the keyboard."),
    ("monitor", "Look at the monitor screen."),
    # Food and Health
    ("healthy", "Eat healthy food daily."),
    ("vitamin", "Take your vitamin daily."),
    ("protein", "Eggs have lots of protein."),
    ("calcium", "Milk has calcium for bones."),
    ("organic", "Buy organic vegetables."),
    ("natural", "Natural food is healthy."),
    ("fitness", "Maintain your fitness level."),
    ("workout", "Do your daily workout."),
    ("exercise", "Exercise makes you strong."),
    ("stretch", "Stretch before exercise."),
    # Additional words
    ("morning", "Wake up early in the morning."),
    ("evening", "The evening sky was orange."),
    ("weekend", "Enjoy your weekend fully."),
    ("holiday", "Plan your holiday well."),
    ("tuesday", "Today is tuesday."),
    ("october", "October brings autumn."),
    ("summer", "Summer is very hot."),
    ("winter", "Winter brings snow."),
    ("spring", "Spring brings flowers."),
    ("autumn", "Autumn leaves fall."),
    ("country", "Visit a new country."),
    ("village", "Life in the village is peaceful."),
    ("city", "The city never sleeps."),
    ("traffic", "Follow the traffic rules."),
    ("station", "Wait at the station."),
    ("airport", "Reach the airport early."),
    ("railway", "Take the railway train."),
    ("highway", "Drive safely on the highway."),
    ("parking", "Find a parking spot."),
    ("building", "The building is tall."),
    ("factory", "Work in the factory."),
    ("hospital", "Visit the hospital."),
    ("college", "Study in college."),
    ("museum", "Visit the museum."),
    ("theater", "Watch a play in theater."),
    ("gallery", "Art gallery shows paintings."),
    ("market", "Shop at the market."),
    ("grocery", "Buy grocery items."),
    ("bakery", "Fresh bread at the bakery."),
    ("butcher", "The butcher cuts meat."),
    ("monday", "Monday starts the week."),
    ("friday", "Friday is the last workday."),
    ("january", "January begins the year."),
    ("august", "August is very warm."),
    ("season", "Which season is this?"),
    ("weather", "Check the weather report."),
    ("sunrise", "Watch the sunrise early."),
    ("sunset", "Enjoy the sunset view."),
    ("rainbow", "Look at the rainbow."),
    ("thunder", "Thunder is very loud."),
    ("subject", "Which subject do you like?"),
    ("english", "Learn English well."),
    ("science", "Science is interesting."),
    ("history", "Study history facts."),
    ("biology", "Learn about biology."),
    ("physics", "Physics laws are cool."),
    ("algebra", "Solve algebra problems."),
    ("grammar", "Follow grammar rules."),
    ("spelling", "Practice spelling daily."),
    ("reading", "Reading is important."),
    ("writing", "Improve your writing."),
    ("drawing", "Practice drawing skills."),
    ("playing", "Playing is fun."),
    ("singing", "Singing makes us happy."),
    ("dancing", "Dancing is exercise."),
    ("running", "Running is healthy."),
    ("jumping", "Jumping builds strength."),
    ("walking", "Walking is good exercise."),
    ("cycling", "Go cycling in the park."),
    ("swimming", "Swimming is refreshing."),
    ("tuesday", "Tuesday is busy."),
    ("sunday", "Sunday is holiday."),
    ("march", "March brings spring."),
    ("april", "April has showers."),
    ("cloudy", "Today is cloudy."),
    ("rainy", "It's a rainy day."),
    ("snowy", "Enjoy the snowy day."),
    ("windy", "It's very windy."),
    ("foggy", "Drive slow in foggy weather."),
    ("stormy", "Stay in during storms."),
    ("teacher", "Listen to your teacher."),
    ("student", "Be a good student."),
    ("library", "Visit the library."),
    ("picture", "Draw a nice picture."),
    ("painting", "Make a painting."),
    ("cooking", "Cooking is an art."),
    ("baking", "Baking smells good."),
    ("cleaning", "Help with cleaning."),
    ("washing", "Finish washing dishes."),
    ("packing", "Start packing early."),
    # More additional words
    ("comfort", "Find comfort here."),
    ("command", "Follow the command."),
    ("comment", "Leave a comment."),
    ("company", "Start a company."),
    ("compare", "Compare prices first."),
    ("compete", "Compete fairly."),
    ("compose", "Compose music."),
    ("concert", "Attend the concert."),
    ("conduct", "Conduct research."),
    ("confirm", "Confirm your booking."),
    ("connect", "Connect the dots."),
    ("consist", "Consist of parts."),
    ("contact", "Contact us today."),
    ("contain", "Contain the spread."),
    ("content", "Create content."),
    ("control", "Control yourself."),
    ("convert", "Convert to digital."),
    ("cooking", "Cooking is fun."),
    ("correct", "Correct your mistakes."),
    ("council", "Join the council."),
    ("country", "Love your country."),
    ("courage", "Show your courage."),
    ("cousin", "Visit your cousin."),
    ("culture", "Learn new culture."),
    ("current", "Check current news."),
    ("cushion", "Soft cushion here."),
    ("customs", "Follow customs."),
    ("cutting", "Cutting vegetables."),
    ("dancing", "Dancing is fun."),
    ("deliver", "Deliver the mail."),
    # Final set of words
    ("develop", "Develop skills."),
    ("diamond", "Shiny diamond."),
    ("digital", "Digital world."),
    ("dinner", "Enjoy dinner."),
    ("direct", "Go direct."),
    ("display", "Display work."),
    ("distant", "Distant land."),
    ("divide", "Divide equally."),
    ("doctor", "Visit doctor."),
    ("dolphin", "Playful dolphin."),
    ("drawing", "Nice drawing."),
    ("driving", "Safe driving."),
    ("dynamic", "Dynamic moves."),
    ("eastern", "Eastern side."),
    ("economy", "Strong economy."),
    ("edition", "New edition."),
    ("element", "Basic element."),
    ("emotion", "Show emotion."),
    ("energy", "Save energy."),
    ("english", "Learn English."),
    ("evening", "Good evening."),
    ("example", "Good example."),
    ("excited", "Feel excited."),
    ("express", "Express yourself."),
    ("extreme", "Extreme sports."),
    ("factory", "Big factory."),
    ("failure", "Learn from failure."),
    ("fashion", "Latest fashion."),
    ("feature", "Special feature."),
    ("feeling", "Good feeling."),
    # Final set of additional seven-letter words
    ("farming", "Farming is hard work."),
    ("fashion", "Fashion trends change."),
    ("fatigue", "Feel fatigue now."),
    ("fearful", "Don't be fearful."),
    ("feeding", "Feeding the birds."),
    ("feeling", "Express your feeling."),
    ("fertile", "Fertile soil here."),
    ("fiction", "Read fiction books."),
    ("fifteen", "Count to fifteen."),
    ("filling", "Filling the form."),
    ("filming", "Filming the scene."),
    ("finance", "Manage finance well."),
    ("finding", "Finding solutions."),
    ("fishing", "Gone fishing today."),
    ("fitting", "Fitting the dress."),
    ("flaming", "Flaming hot food."),
    ("flashed", "Light flashed bright."),
    ("flatten", "Flatten the dough."),
    ("flavour", "Great flavour here."),
    ("flexing", "Flexing muscles."),
    ("flipped", "Flipped the page."),
    ("flowing", "River flowing fast."),
    ("fluting", "Fluting music."),
    ("focused", "Stay focused now."),
    ("folding", "Folding clothes."),
    ("fondant", "Make fondant cake."),
    ("fooling", "Stop fooling around."),
    ("forcing", "Forcing is wrong."),
    ("foreign", "Foreign language."),
    ("forging", "Forging ahead."),
    ("forming", "Forming a team."),
    ("forward", "Move forward now."),
    ("freedom", "Value freedom."),
    ("freezer", "Check the freezer."),
    ("freshen", "Freshen the air."),
    ("friends", "Make new friends."),
    ("frisbee", "Throw the frisbee."),
    ("frosted", "Frosted glass."),
    ("frowned", "She frowned at me."),
    ("frugal", "Live frugal life."),
    ("fueling", "Fueling the car."),
    ("fulfill", "Fulfill your dreams."),
    ("fumbled", "Fumbled the ball."),
    ("funding", "Secure funding."),
    ("funeral", "Attend the funeral."),
    ("furnace", "Check the furnace."),
    ("furnish", "Furnish the room."),
    ("further", "Go further ahead."),
    ("furtive", "Furtive glances."),
    ("fusion", "Fusion cuisine."),
    ("gaining", "Gaining strength."),
    ("gallery", "Visit the gallery."),
    ("gallons", "Many gallons."),
    ("gallop", "Horses gallop fast."),
    ("gambled", "Never gambled."),
    ("gaming", "Gaming is fun."),
    ("garbage", "Take out garbage."),
    ("garbled", "Garbled message."),
    ("garden", "Beautiful garden."),
    ("garlic", "Add some garlic."),
    ("garment", "New garment."),
    ("gateway", "Through the gateway."),
    ("gather", "Gather together."),
    ("gazing", "Gazing at stars."),
    ("general", "General meeting."),
    ("genetic", "Genetic research."),
    ("genuine", "Genuine person."),
    ("gesture", "Kind gesture."),
    ("getting", "Getting better."),
    ("gifted", "Gifted student."),
    ("giggled", "She giggled."),
    ("ginger", "Fresh ginger."),
    ("glanced", "Glanced at watch."),
    ("glaring", "Glaring sun."),
    ("glasses", "Wear your glasses."),
    ("gleamed", "Metal gleamed."),
    ("glimpse", "Catch a glimpse."),
    ("glisten", "Stars glisten."),
    ("glowing", "Glowing ember."),
    ("glucose", "Check glucose."),
]

NINE_LETTER_WORDS = [
    # Nature and Animals
    ("butterfly", "A butterfly has colorful wings."),
    ("dragonfly", "The dragonfly darted over water."),
    ("crocodile", "A crocodile lives in the river."),
    ("kangaroo", "A kangaroo hops in Australia."),
    ("dinosaur", "Dinosaurs lived long ago."),
    ("ladybird", "The ladybird has spots."),
    ("scorpion", "A scorpion has a stinger."),
    ("seahorse", "The seahorse swims slowly."),
    ("flamingo", "The flamingo stands on one leg."),
    ("penguin", "Penguins live in Antarctica."),
    # Food and Fruits
    ("pineapple", "Pineapple is a tropical fruit."),
    ("chocolate", "Dark chocolate is healthy."),
    ("strawberry", "The strawberry was sweet and red."),
    ("blueberry", "Blueberries are good for health."),
    ("cranberry", "Cranberry juice is tart."),
    ("vegetable", "Eat your vegetables daily."),
    ("nutrition", "Good nutrition is important."),
    ("delicious", "The meal was delicious."),
    ("breakfast", "Breakfast is important."),
    ("appetizer", "Start with an appetizer."),
    # Personal Qualities
    ("beautiful", "The garden was beautiful in spring."),
    ("confident", "Be confident in yourself."),
    ("dedicated", "Stay dedicated to your goals."),
    ("energetic", "The puppy was very energetic."),
    ("excellent", "She did an excellent job."),
    ("fortunate", "We are fortunate to learn."),
    ("generous", "It's good to be generous."),
    ("graceful", "The dancer was graceful."),
    ("innocent", "Children are innocent."),
    ("positive", "Keep a positive attitude."),
    # Education and Learning
    ("education", "Education is very important."),
    ("knowledge", "Gain knowledge through reading."),
    ("learning", "Learning is a lifelong process."),
    ("practice", "Practice makes perfect."),
    ("progress", "Track your progress daily."),
    ("question", "Ask questions when confused."),
    ("research", "Do research carefully."),
    ("studying", "Studying helps you improve."),
    ("teaching", "Teaching is a noble profession."),
    ("training", "Training improves skills."),
    # Actions and Activities
    ("challenge", "Accept the challenge with courage."),
    ("determine", "Determine your path in life."),
    ("influence", "Parents influence their children."),
    ("organize", "Organize your tasks efficiently."),
    ("celebrate", "Let's celebrate your success."),
    ("exercise", "Do regular exercise."),
    ("discover", "Scientists discover new things."),
    ("adventure", "Every day is a new adventure."),
    ("explore", "Explore new places."),
    ("perform", "Perform on the stage."),
    # Environment
    ("mountain", "We climbed the mountain high."),
    ("waterfall", "The waterfall was majestic."),
    ("rainforest", "Rainforests need protection."),
    ("snowflake", "Each snowflake is unique."),
    ("universe", "The universe is vast."),
    ("pollution", "Reduce air pollution."),
    ("recycle", "Recycle paper and plastic."),
    ("preserve", "Preserve natural resources."),
    ("environment", "Protect the environment."),
    ("ecosystem", "Maintain the ecosystem."),
    # Technology
    ("computer", "Use the computer carefully."),
    ("internet", "The internet connects people."),
    ("software", "Install new software."),
    ("telephone", "Answer the telephone."),
    ("technology", "Technology changes rapidly."),
    ("wireless", "Connect to wireless network."),
    ("database", "Store data in database."),
    ("password", "Keep your password secret."),
    ("keyboard", "Type on the keyboard."),
    ("download", "Download the new update."),
    # Abstract Concepts
    ("different", "Everyone is different and unique."),
    ("important", "Time is very important."),
    ("potential", "Everyone has potential to grow."),
    ("strength", "Inner strength helps in tough times."),
    ("thankful", "Be thankful for what you have."),
    ("happiness", "Spread happiness to others."),
    ("kindness", "Show kindness to everyone."),
    ("patience", "Patience is a virtue."),
    ("peaceful", "Maintain a peaceful mind."),
    ("creative", "Be creative in your work."),
    # Additional words
    ("classroom", "The classroom was quiet."),
    ("bookstore", "Visit the bookstore today."),
    ("cafeteria", "Eat in the cafeteria."),
    ("principal", "Meet the principal."),
    ("professor", "The professor teaches well."),
    ("scientist", "Become a scientist."),
    ("architect", "Design as an architect."),
    ("engineer", "Work as an engineer."),
    ("astronaut", "Become an astronaut."),
    ("musician", "Play as a musician."),
    ("artist", "Paint like an artist."),
    ("gardener", "Work as a gardener."),
    ("carpenter", "Build as a carpenter."),
    ("policeman", "Thank the policeman."),
    ("firefight", "Brave firefighters help."),
    ("paramedic", "Call the paramedic."),
    ("librarian", "Ask the librarian."),
    ("secretary", "The secretary helps."),
    ("president", "Elect the president."),
    ("governor", "Meet the governor."),
    ("chemistry", "Study chemistry well."),
    ("geography", "Learn geography maps."),
    ("geometry", "Solve geometry problems."),
    ("arithmetic", "Practice arithmetic."),
    ("languages", "Learn new languages."),
    ("literature", "Read literature books."),
    ("economics", "Study economics."),
    ("sociology", "Learn sociology."),
    ("psychology", "Understand psychology."),
    ("astronomy", "Study astronomy stars."),
    ("butterfly", "The butterfly is pretty."),
    ("grassland", "Animals live in grassland."),
    ("rainforest", "Protect the rainforest."),
    ("mountains", "Climb the mountains high."),
    ("seashore", "Walk on the seashore."),
    ("dinosaur", "Learn about dinosaurs."),
    ("elephant", "An elephant is huge."),
    ("crocodile", "Watch the crocodile swim."),
    ("penguin", "Penguins love cold weather."),
    ("octopus", "An octopus has eight arms."),
    ("vegetable", "Eat your vegetables."),
    ("breakfast", "Eat healthy breakfast."),
    ("chocolate", "Dark chocolate is good."),
    ("icecream", "Enjoy your icecream."),
    ("sandwich", "Make a sandwich."),
    ("medicine", "Take your medicine."),
    ("exercise", "Do regular exercise."),
    ("hospital", "Visit the hospital."),
    ("ambulance", "Call an ambulance."),
    ("treatment", "Get proper treatment."),
    ("telephone", "Answer the telephone."),
    ("computer", "Use the computer well."),
    ("internet", "Browse the internet."),
    ("keyboard", "Type on the keyboard."),
    ("printer", "Use the printer carefully."),
    ("textbook", "Read your textbook."),
    ("notebook", "Write in your notebook."),
    ("pencil", "Sharpen your pencil."),
    ("backpack", "Pack your backpack."),
    ("umbrella", "Take your umbrella."),
    ("beautiful", "The flower is beautiful."),
    ("wonderful", "Life is wonderful."),
    ("excellent", "Your work is excellent."),
    ("different", "Everyone is different."),
    ("important", "This is important."),
    ("difficult", "The test was difficult."),
    ("delicious", "The food is delicious."),
    ("dangerous", "Be careful of dangerous things."),
    ("fantastic", "You did a fantastic job."),
    ("brilliant", "That's a brilliant idea."),
    ("classroom", "Keep the classroom clean."),
    ("lunchroom", "Eat in the lunchroom."),
    ("bathroom", "Clean the bathroom."),
    ("bedroom", "Tidy your bedroom."),
    ("playroom", "Play in the playroom."),
    ("bookshelf", "Arrange the bookshelf."),
    ("furniture", "Move the furniture."),
    ("appliance", "Fix the appliance."),
    ("staircase", "Use the staircase."),
    ("doorbell", "Ring the doorbell."),
    # More additional words
    ("discover", "Discover new places."),
    ("discuss", "Discuss the topic."),
    ("distance", "Keep your distance."),
    ("district", "Visit the district."),
    ("division", "Learn division."),
    ("document", "Sign the document."),
    ("domestic", "Domestic animals."),
    ("dominate", "Dominate the game."),
    ("download", "Download the file."),
    ("dramatic", "Dramatic scene."),
    ("drawing", "Nice drawing."),
    ("drinking", "Drinking water."),
    ("driving", "Safe driving."),
    ("duration", "Check duration."),
    ("dynamics", "Study dynamics."),
    ("earnings", "Count earnings."),
    ("economic", "Economic growth."),
    ("educated", "Stay educated."),
    ("election", "Vote in election."),
    ("electric", "Electric power."),
    ("elephant", "Big elephant."),
    ("elevator", "Take elevator."),
    ("eligible", "Check if eligible."),
    ("emphasis", "Place emphasis."),
    ("employee", "Happy employee."),
    ("engineer", "The engineer builds."),
    ("envelope", "Seal the envelope."),
    ("estimate", "Estimate the cost."),
    ("evaluate", "Evaluate results."),
    ("everyday", "Everyday tasks."),
    # Final set of words
    ("exercise", "Daily exercise."),
    ("exciting", "Exciting game."),
    ("exchange", "Fair exchange."),
    ("existing", "Existing rules."),
    ("expected", "Expected result."),
    ("explicit", "Be explicit."),
    ("external", "External factors."),
    ("facility", "Use facility."),
    ("familiar", "Familiar face."),
    ("favorite", "My favorite."),
    ("february", "Cold February."),
    ("feedback", "Give feedback."),
    ("festival", "Fun festival."),
    ("fighting", "Stop fighting."),
    ("finished", "Task finished."),
    ("flexible", "Stay flexible."),
    ("floating", "Floating leaf."),
    ("football", "Play football."),
    ("forecast", "Weather forecast."),
    ("forward", "Move forward."),
    ("frequent", "Frequent visits."),
    ("friendly", "Be friendly."),
    ("function", "Basic function."),
    ("generous", "Be generous."),
    ("graduate", "Graduate soon."),
    ("graphics", "Cool graphics."),
    ("grateful", "Feel grateful."),
    ("guidance", "Seek guidance."),
    ("hardware", "New hardware."),
    ("heritage", "Rich heritage."),
    ("excellent", "Excellent work."),
    ("exception", "Make an exception."),
    ("exchange", "Exchange ideas."),
    ("exclusive", "Exclusive offer."),
    ("exercise", "Daily exercise is healthy."),
    # Final set of additional nine-letter words
    ("excellent", "Excellent work."),
    ("exception", "Make an exception."),
    ("exchange", "Exchange ideas."),
    ("exclusive", "Exclusive offer."),
    ("exercise", "Daily exercise."),
    ("existence", "Proof of existence."),
    ("expansion", "Business expansion."),
    ("expensive", "Too expensive."),
    ("expertise", "Great expertise."),
    ("explained", "Well explained."),
    ("exploring", "Keep exploring."),
    ("explosion", "Loud explosion."),
    ("expressed", "Well expressed."),
    ("extending", "Extending help."),
    ("extension", "File extension."),
    ("extensive", "Extensive research."),
    ("extracted", "Oil extracted."),
    ("extremely", "Extremely good."),
    ("eyebrows", "Raise eyebrows."),
    ("fabulous", "Fabulous dress."),
    ("facilitate", "Facilitate growth."),
    ("factories", "Many factories."),
    ("factoring", "Factoring numbers."),
    ("faithful", "Stay faithful."),
    ("fantastic", "Fantastic view."),
    ("fastening", "Fastening belt."),
    ("favorable", "Favorable weather."),
    ("favourite", "My favourite."),
    ("featuring", "Featuring stars."),
    ("feminine", "Feminine style."),
    ("fermented", "Fermented food."),
    ("festivity", "Join festivity."),
    ("fetching", "Fetching water."),
    ("fictional", "Fictional story."),
    ("fifteenth", "Fifteenth place."),
    ("fighting", "Stop fighting."),
    ("figurine", "Clay figurine."),
    ("filtering", "Filtering water."),
    ("finalized", "Finalized deal."),
    ("financial", "Financial plan."),
    ("finishing", "Finishing work."),
    ("fireworks", "Watch fireworks."),
    ("firsthand", "Firsthand experience."),
    ("fisherman", "Old fisherman."),
    ("flashing", "Flashing lights."),
    ("flattering", "Flattering words."),
    ("flavoring", "Food flavoring."),
    ("flickering", "Flickering flame."),
    ("fluttered", "Flag fluttered."),
    ("following", "Following rules."),
    ("forbidden", "Forbidden fruit."),
    ("forceful", "Forceful wind."),
    ("foreigner", "Welcome foreigner."),
    ("foresight", "Good foresight."),
    ("forgetting", "Stop forgetting."),
    ("forgiving", "Forgiving nature."),
    ("forgotten", "Forgotten tale."),
    ("formation", "Team formation."),
    ("formative", "Formative years."),
    ("fortified", "Fortified wall."),
    ("fortunate", "Feel fortunate."),
    ("forwarded", "Forwarded mail."),
    ("fostering", "Fostering talent."),
    ("foundling", "Lost foundling."),
    ("fountains", "Water fountains."),
    ("fragrance", "Sweet fragrance."),
    ("framework", "Solid framework."),
    ("franchise", "New franchise."),
    ("freehand", "Draw freehand."),
    ("freestyle", "Swim freestyle."),
    ("frequency", "High frequency."),
    ("freshness", "Morning freshness."),
    ("friendship", "True friendship."),
    ("frightful", "Frightful scene."),
    ("frostbite", "Avoid frostbite."),
    ("fruitful", "Fruitful day."),
    ("frustrated", "Feel frustrated."),
    ("fulfilling", "Fulfilling life."),
    ("furnished", "Well furnished."),
]

# class Command(BaseCommand):
#     help = "Inserts 15 unique words and sentences per day (5 words each of 5, 7, and 9 letters)."

#     def handle(self, *args, **kwargs):
#         # Clear existing data first
#         Spellbee.objects.all().delete()
#         self.stdout.write(self.style.SUCCESS("Cleared existing data."))
        
#         # Start from today
#         start_date = datetime.date.today()
        
#         # Create copies of word lists to avoid modifying originals
#         available_five = FIVE_LETTER_WORDS[:]
#         available_seven = SEVEN_LETTER_WORDS[:]
#         available_nine = NINE_LETTER_WORDS[:]

#         # Calculate how many words we need
#         days_needed = 59
#         words_per_category_per_day = 5
#         total_words_needed = days_needed * words_per_category_per_day

#         # Verify we have enough words
#         if len(available_five) < total_words_needed:
#             self.stdout.write(self.style.ERROR(f"Not enough five-letter words. Have {len(available_five)}, need {total_words_needed}"))
#             return
#         if len(available_seven) < total_words_needed:
#             self.stdout.write(self.style.ERROR(f"Not enough seven-letter words. Have {len(available_seven)}, need {total_words_needed}"))
#             return
#         if len(available_nine) < total_words_needed:
#             self.stdout.write(self.style.ERROR(f"Not enough nine-letter words. Have {len(available_nine)}, need {total_words_needed}"))
#             return

#         days_inserted = 0
#         used_words = set()
        
#         for i in range(days_needed):
#             entry_date = start_date + datetime.timedelta(days=i)

#             try:
#                 # Select 5 words from each category
#                 five_letter = random.sample([w for w in available_five if w[0] not in used_words], 5)
#                 seven_letter = random.sample([w for w in available_seven if w[0] not in used_words], 5)
#                 nine_letter = random.sample([w for w in available_nine if w[0] not in used_words], 5)

#                 # Combine all selected entries
#                 selected_entries = five_letter + seven_letter + nine_letter
#                 words, sentences = zip(*selected_entries)

#                 # Add used words to set
#                 used_words.update(words)

#                 # Insert into database
#                 Spellbee.objects.create(
#                     spellbee_date=entry_date,
#                     words=list(words),
#                     sentences=list(sentences)
#                 )
#                 days_inserted += 1
#                 self.stdout.write(self.style.SUCCESS(
#                     f"Inserted for {entry_date}: "
#                     f"5 five-letter words, 5 seven-letter words, 5 nine-letter words"
#                 ))

#             except ValueError as e:
#                 self.stdout.write(self.style.ERROR(
#                     f"Error on day {i+1}: {str(e)}"
#                 ))
#                 break
        
#         self.stdout.write(self.style.SUCCESS(f"\nTotal days of data inserted: {days_inserted}"))





# ... keep your existing word lists (FIVE_LETTER_WORDS, SEVEN_LETTER_WORDS, NINE_LETTER_WORDS) ...

class Command(BaseCommand):
    help = "Inserts 15 unique words and sentences per day (5 words each of 5, 7, and 9 letters) for 365 days."

    def handle(self, *args, **kwargs):
        # Clear existing data first
        Spellbee.objects.all().delete()
        self.stdout.write(self.style.SUCCESS("Cleared existing data."))
        
        # Start from today
        start_date = datetime.date.today()
        
        # Set number of days to 365
        days_needed = 365
        words_per_category_per_day = 5

        days_inserted = 0
        
        for i in range(days_needed):
            entry_date = start_date + datetime.timedelta(days=i)

            try:
                # For each day, select 5 random words from each category
                # Note: removed the uniqueness across days constraint
                five_letter = random.sample(FIVE_LETTER_WORDS, 5)
                seven_letter = random.sample(SEVEN_LETTER_WORDS, 5)
                nine_letter = random.sample(NINE_LETTER_WORDS, 5)

                # Combine all selected entries
                selected_entries = five_letter + seven_letter + nine_letter
                words, sentences = zip(*selected_entries)

                # Insert into database
                Spellbee.objects.create(
                    spellbee_date=entry_date,
                    words=list(words),
                    sentences=list(sentences)
                )
                days_inserted += 1
                self.stdout.write(self.style.SUCCESS(
                    f"Inserted for {entry_date}: "
                    f"5 five-letter words, 5 seven-letter words, 5 nine-letter words"
                ))

            except Exception as e:
                self.stdout.write(self.style.ERROR(
                    f"Error on day {i+1}: {str(e)}"
                ))
                break
        
        self.stdout.write(self.style.SUCCESS(f"\nTotal days of data inserted: {days_inserted}"))